runtime: python39

env_variables:
  DB_USER: "postgres"
  DB_PASS: "root"
  DB_NAME: "menu_table"
  CLOUD_SQL_CONNECTION_NAME: "cumulonimbus-439521:us-central1:cumulonimbus-cloud-sql	"

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
